//#define  _Exit(__VA_ARGS__)
//#define  a64l(__VA_ARGS__)
#define potrat(...)		abort(__VA_ARGS__)
//#define  abs(__VA_ARGS__)
#define přiútěku(...)	atexit(__VA_ARGS__)
//#define  atof(__VA_ARGS__)
//#define  atoi(__VA_ARGS__)
//#define  atol(__VA_ARGS__)
//#define  atoll(__VA_ARGS__)
//#define  bsearch(const void *, const void *, size_t, size_t,
#define čnavalp(...)	calloc(__VA_ARGS__)  //naval čistou paměť
#define rozděl(...)		div(__VA_ARGS__)
//#define  drand48(__VA_ARGS__)
//#define  ecvt(__VA_ARGS__) (LEGACY )
//#define  erand48(__VA_ARGS__)
#define vemroha(...)	exit(__VA_ARGS__)
//#define  fcvt(__VA_ARGS__) (LEGACY )
#define zdarmap(...)	free(__VA_ARGS__)  //free memory (paměť zdarma)
//#define  gcvt(__VA_ARGS__) (LEGACY )
//#define  getenv(__VA_ARGS__)
//#define  getsubopt(__VA_ARGS__)
//#define  grantpt(__VA_ARGS__)
//#define  initstate(__VA_ARGS__)
//#define  jrand48(__VA_ARGS__)
//#define  l64a(__VA_ARGS__)
//#define  labs(__VA_ARGS__)
//#define  lcong48(__VA_ARGS__)
//#define  ldiv(__VA_ARGS__)
//#define  llabs(__VA_ARGS__)
//#define  lldiv(__VA_ARGS__)
//#define  lrand48(__VA_ARGS__)
#define navalp(...)		malloc(__VA_ARGS__) //naval paměť
//#define  mblen(__VA_ARGS__)
//#define  mbstowcs(__VA_ARGS__)
//#define  mbtowc(__VA_ARGS__)
//#define  mktemp(__VA_ARGS__) (LEGACY )
//#define  mkstemp(__VA_ARGS__)
//#define  mrand48(__VA_ARGS__)
//#define  nrand48(__VA_ARGS__)
//#define  posix_memalign(__VA_ARGS__)
//#define  posix_openpt(__VA_ARGS__)
//#define  ptsname(__VA_ARGS__)
//#define  putenv(__VA_ARGS__)
//#define  qsort(void *, size_t, size_t, int (*)(const void *,
#define náhoda(...)			rand(__VA_ARGS__)
//#define  rand_r(__VA_ARGS__)
//#define  random(__VA_ARGS__)
#define znavalp(...)		realloc(__VA_ARGS__) //znovu naval paměť
#define pravácesta(...)		realpath(__VA_ARGS__)
//#define  seed48(__VA_ARGS__)
//#define  setenv(__VA_ARGS__)
//#define  setkey(__VA_ARGS__)
//#define  setstate(__VA_ARGS__)
#define skoronáhoda(...)		srand(__VA_ARGS__)
//#define  srand48(__VA_ARGS__)
//#define  srandom(__VA_ARGS__)
#define řetnacv(...)		strtod(__VA_ARGS__)
#define řetnapl(...)		strtof(__VA_ARGS__)
#define řetnadl(...)		strtol(__VA_ARGS__)
#define řetnadcv(...)		strtold(__VA_ARGS__)
#define řetnahdl(...)		strtoll(__VA_ARGS__)
#define řetnandl(...)		strtoul(__VA_ARGS__)
#define řetnanhdl(...)		strtoull(__VA_ARGS__)
//#define  system(__VA_ARGS__)
//#define  unlockpt(__VA_ARGS__)
//#define  unsetenv(__VA_ARGS__)
//#define  wcstombs(__VA_ARGS__)
//#define  wctomb(__VA_ARGS__)
